"""empty message

Revision ID: 1afb776a8e91
Revises: ede073f81e0b
Create Date: 2022-12-03 13:50:52.326519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afb776a8e91'
down_revision = 'ede073f81e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snap_email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('snap_phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('snap_phone')
        batch_op.drop_column('snap_email')

    # ### end Alembic commands ###
