"""empty message

Revision ID: 29db81ca318d
Revises: b313fcd6e37c
Create Date: 2022-12-03 13:04:13.915562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29db81ca318d'
down_revision = 'b313fcd6e37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('most_received', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_types', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top10_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('top10_text')
        batch_op.drop_column('media_types')
        batch_op.drop_column('most_received')

    # ### end Alembic commands ###
