"""empty message

Revision ID: 4584e821a172
Revises: a9f93fed9b15
Create Date: 2022-12-10 12:13:56.716406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4584e821a172'
down_revision = 'a9f93fed9b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breakdown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('engagement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('num_of_interests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name_changes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link_to_memory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first_memory_string', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_subs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publishers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('public_users', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_snaps_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_snaps_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_snaps_saved', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_snaps_saved')
        batch_op.drop_column('total_snaps_received')
        batch_op.drop_column('total_snaps_sent')
        batch_op.drop_column('public_users')
        batch_op.drop_column('publishers')
        batch_op.drop_column('stories')
        batch_op.drop_column('total_subs')
        batch_op.drop_column('first_memory_string')
        batch_op.drop_column('link_to_memory')
        batch_op.drop_column('name_changes')
        batch_op.drop_column('num_of_interests')
        batch_op.drop_column('engagement')
        batch_op.drop_column('breakdown')

    # ### end Alembic commands ###
