"""empty message

Revision ID: 56db119277f5
Revises: 4d069f0e8112
Create Date: 2022-10-30 16:52:03.381450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56db119277f5'
down_revision = '4d069f0e8112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filename', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'data')
    op.drop_column('users', 'filename')
    # ### end Alembic commands ###
