"""empty message

Revision ID: 57763f8dc41e
Revises: b04454524e9f
Create Date: 2022-11-25 10:32:47.549414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57763f8dc41e'
down_revision = 'b04454524e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recent_location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recent_snap', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recent_snap')
        batch_op.drop_column('recent_location')

    # ### end Alembic commands ###
