"""empty message

Revision ID: ae76d1bd8ee0
Revises: 4584e821a172
Create Date: 2022-12-10 16:54:58.069419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae76d1bd8ee0'
down_revision = '4584e821a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_friend', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('first5_friends', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('story_array', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('story_array')
        batch_op.drop_column('first5_friends')
        batch_op.drop_column('first_friend')

    # ### end Alembic commands ###
