"""empty message

Revision ID: b313fcd6e37c
Revises: a0ad991ac6cd
Create Date: 2022-12-01 13:05:01.730901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b313fcd6e37c'
down_revision = 'a0ad991ac6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('most_received', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_types', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top10_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('top10_text')
        batch_op.drop_column('media_types')
        batch_op.drop_column('most_received')

    # ### end Alembic commands ###
