"""empty message

Revision ID: bfac3fdfacfd
Revises: f553e19d0948
Create Date: 2022-12-11 18:24:19.797771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfac3fdfacfd'
down_revision = 'f553e19d0948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_received_ratio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('received_sent_ratio', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_location', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('random_location')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('received_sent_ratio')
        batch_op.drop_column('sent_received_ratio')

    # ### end Alembic commands ###
