"""empty message

Revision ID: c44591af59b3
Revises: 57763f8dc41e
Create Date: 2022-11-25 16:34:41.391072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44591af59b3'
down_revision = '57763f8dc41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequent_locations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('frequent_locations')

    # ### end Alembic commands ###
