"""empty message

Revision ID: f553e19d0948
Revises: 71f85978d86a
Create Date: 2022-12-11 14:26:40.532873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f553e19d0948'
down_revision = '71f85978d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('opened_app', sa.Integer(), nullable=True),
    sa.Column('discover_stories', sa.Integer(), nullable=True),
    sa.Column('snaps_to_story', sa.Integer(), nullable=True),
    sa.Column('total_snaps_viewed', sa.Integer(), nullable=True),
    sa.Column('snaps_sent', sa.Integer(), nullable=True),
    sa.Column('snaps_viewed', sa.Integer(), nullable=True),
    sa.Column('chats_sent', sa.Integer(), nullable=True),
    sa.Column('chats_viewed', sa.Integer(), nullable=True),
    sa.Column('discover_editions', sa.Integer(), nullable=True),
    sa.Column('discover_snaps', sa.Integer(), nullable=True),
    sa.Column('direct_snaps_viewed', sa.Integer(), nullable=True),
    sa.Column('direct_snaps_created', sa.Integer(), nullable=True),
    sa.Column('geofilter_snaps', sa.Integer(), nullable=True),
    sa.Column('geofilter_story', sa.Integer(), nullable=True),
    sa.Column('geolens_snaps', sa.Integer(), nullable=True),
    sa.Column('geofilter_used', sa.Integer(), nullable=True),
    sa.Column('geofilter_swipes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement')
    # ### end Alembic commands ###
